import { prisma } from '../src/prisma';

const merchantsData = [
  {
    memberNo: 'LC-MBR-2026-001',
    businessName: 'Restoran Selera Kampung Warisan Sdn Bhd',
    fullName: 'Haji Razak bin Bakar',
    registrationNo: '202401039821-M',
    icPassportNo: '760412-10-5329',
    dateOfBirth: '12/04/1976',
    age: '50',
    gender: 'Lelaki',
    race: 'Melayu',
    religion: 'Islam',
    contactNumber: '+60 19-334 5671',
    emailAddress: 'warisankampung.ss15@gmail.com',
    storeAddress: 'No 12, Ground Floor, Jalan SS15/4D, 47500 Subang Jaya, Selangor',
    operatingDays: 'Isnin hingga Sabtu (Ahad Tutup)',
    operatingHours: '08:00 - 22:00',
    typeOfFood: 'Masakan Melayu Kampung, Lauk Campur & Mee Kari',
    bankName: 'CIMB Bank Berhad',
    bankAccountName: 'Restoran Selera Kampung Warisan Sdn Bhd',
    bankAccountNumber: '800923451298',
    status: 'Diluluskan',
    agentName: 'Faizal bin Mohamad Radzi',
    date: new Date('2026-09-01T10:00:00Z'),
    yesScore: 9,
    leadStatus: 'Hot Lead',
    targetPlatform: 'GrabFood & ShopeeFood',
    notes: 'Peniaga sangat bersemangat. Lokasi strategik berdekatan kolej swasta dan pejabat.',
  },
  {
    memberNo: 'LC-MBR-2026-002',
    businessName: 'Mee Tarik Jalan Sultan Enterprise',
    fullName: 'Chen Wei Loon',
    registrationNo: '002938411-V',
    icPassportNo: '880620-14-5109',
    dateOfBirth: '20/06/1988',
    age: '38',
    gender: 'Lelaki',
    race: 'Cina',
    religion: 'Buddha',
    contactNumber: '+60 16-228 9012',
    emailAddress: 'meetarik.sultan@yahoo.com',
    storeAddress: 'Lot 4, Jalan Sultan, City Centre, 50000 Kuala Lumpur',
    operatingDays: 'Setiap Hari (Isnin - Ahad)',
    operatingHours: '10:30 - 23:00',
    typeOfFood: 'Mee Tarik Segar, Sup Daging & Dumpling Kukus',
    bankName: 'Public Bank Berhad',
    bankAccountName: 'Mee Tarik Jalan Sultan Enterprise',
    bankAccountNumber: '3194029410',
    status: 'Dalam Proses',
    agentName: 'Faizal bin Mohamad Radzi',
    date: new Date('2026-09-02T11:15:00Z'),
    yesScore: 8,
    leadStatus: 'Qualified Lead',
    targetPlatform: 'Foodpanda & GrabFood',
    notes: 'Trafik pejalan kaki yang sangat tinggi di kawasan pelancong Jalan Sultan.',
  },
  {
    memberNo: 'LC-MBR-2026-003',
    businessName: 'Nasi Kandar Subang Royale Sdn Bhd',
    fullName: 'Mohamed Farook bin Abdul Malik',
    registrationNo: '202301048892-A',
    icPassportNo: '820310-07-5421',
    dateOfBirth: '10/03/1982',
    age: '44',
    gender: 'Lelaki',
    race: 'India Muslim',
    religion: 'Islam',
    contactNumber: '+60 17-445 1209',
    emailAddress: 'kandar.subangroyale@gmail.com',
    storeAddress: 'No 85, Jalan USJ 10/1E, Taipan Business Centre, 47620 Subang Jaya',
    operatingDays: '24 Jam (Setiap Hari)',
    operatingHours: '24 Jam',
    typeOfFood: 'Nasi Kandar Tradisional, Kari Kepala Ikan & Ayam Goreng Panas',
    bankName: 'Malayan Banking Berhad (Maybank)',
    bankAccountName: 'Nasi Kandar Subang Royale Sdn Bhd',
    bankAccountNumber: '512839104821',
    status: 'Diluluskan',
    agentName: 'Faizal bin Mohamad Radzi',
    date: new Date('2026-09-03T14:30:00Z'),
    yesScore: 10,
    leadStatus: 'Hot Lead',
    targetPlatform: 'GrabFood',
    notes: 'Premis 2 pintu di tengah kawasan Taipan, kapasiti order harian tinggi.',
  },
  {
    memberNo: 'LC-MBR-2026-004',
    businessName: 'Dapur Nenek Salbiah Enterprise',
    fullName: 'Salbiah binti Hashim',
    registrationNo: '003182940-T',
    icPassportNo: '681123-10-5198',
    dateOfBirth: '23/11/1968',
    age: '58',
    gender: 'Wanita',
    race: 'Melayu',
    religion: 'Islam',
    contactNumber: '+60 13-901 8843',
    emailAddress: 'dapurnenek.salbiah@gmail.com',
    storeAddress: 'Gerai 3, Medan Selera Seksyen 7, 40000 Shah Alam, Selangor',
    operatingDays: 'Isnin - Jumaat',
    operatingHours: '07:30 - 16:30',
    typeOfFood: 'Aneka Lauk Melayu Tradisional, Asam Pedas Melaka & Sambal Ikan',
    bankName: 'Bank Islam Malaysia Berhad',
    bankAccountName: 'Salbiah binti Hashim',
    bankAccountNumber: '120380291823',
    status: 'Diluluskan',
    agentName: 'Faizal bin Mohamad Radzi',
    date: new Date('2026-09-04T09:00:00Z'),
    yesScore: 9,
    leadStatus: 'Qualified Lead',
    targetPlatform: 'ShopeeFood & GrabFood',
    notes: 'Kawasan tumpuan pelajar universiti dan staf hospital Shah Alam.',
  },
  {
    memberNo: 'LC-MBR-2026-005',
    businessName: 'Heritage Hainan Coffee & Toast Kopitiam',
    fullName: 'Tan Kim Hock',
    registrationNo: '202201019283-W',
    icPassportNo: '750914-14-5231',
    dateOfBirth: '14/09/1975',
    age: '51',
    gender: 'Lelaki',
    race: 'Cina',
    religion: 'Buddha',
    contactNumber: '+60 12-663 4519',
    emailAddress: 'heritage.hainancoffee@gmail.com',
    storeAddress: 'No 18, Jalan Petaling, City Centre, 50000 Kuala Lumpur',
    operatingDays: 'Selasa - Ahad (Isnin Tutup)',
    operatingHours: '07:00 - 18:00',
    typeOfFood: 'Kopi Tradisional Hainan, Roti Bakar Kaya & Telur Separuh Masak',
    bankName: 'Hong Leong Bank Berhad',
    bankAccountName: 'Heritage Hainan Coffee & Toast Kopitiam',
    bankAccountNumber: '04800192841',
    status: 'Diluluskan',
    agentName: 'Faizal bin Mohamad Radzi',
    date: new Date('2026-09-05T08:30:00Z'),
    yesScore: 10,
    leadStatus: 'Hot Lead',
    targetPlatform: 'GrabFood',
    notes: 'Jenama kopitiam warisan sejak 1980-an dengan peminat setia.',
  },
  {
    memberNo: 'LC-MBR-2026-006',
    businessName: 'Warisan Nasi Kukus Ayam Dara Sdn Bhd',
    fullName: 'Amirul Hakim bin Zainal',
    registrationNo: '202401059281-K',
    icPassportNo: '900518-10-6019',
    dateOfBirth: '18/05/1990',
    age: '36',
    gender: 'Lelaki',
    race: 'Melayu',
    religion: 'Islam',
    contactNumber: '+60 18-912 3001',
    emailAddress: 'nasikukus.ayamdara@gmail.com',
    storeAddress: 'No 5, Jalan Radin Bagus, Sri Petaling, 57000 Kuala Lumpur',
    operatingDays: 'Setiap Hari',
    operatingHours: '10:00 - 22:00',
    typeOfFood: 'Nasi Kukus Wangi, Ayam Dara Berempah & Sambal Belacan Berapi',
    bankName: 'Malayan Banking Berhad (Maybank)',
    bankAccountName: 'Warisan Nasi Kukus Ayam Dara Sdn Bhd',
    bankAccountNumber: '164019284019',
    status: 'Diluluskan',
    agentName: 'Siti Sarah binti Yusoff',
    date: new Date('2026-09-06T11:00:00Z'),
    yesScore: 10,
    leadStatus: 'Hot Lead',
    targetPlatform: 'GrabFood',
    notes: 'Volum penghantaran waktu makan tengah hari sangat padu di Sri Petaling.',
  },
  {
    memberNo: 'LC-MBR-2026-007',
    businessName: 'Kopitiam Ah Kow 1958 Enterprise',
    fullName: 'Kow Chee Meng',
    registrationNo: '001982341-X',
    icPassportNo: '650204-10-5819',
    dateOfBirth: '04/02/1965',
    age: '61',
    gender: 'Lelaki',
    race: 'Cina',
    religion: 'Buddha',
    contactNumber: '+60 12-384 9901',
    emailAddress: 'ahkow1958.pudu@gmail.com',
    storeAddress: 'No 22, Jalan Pasar, Pudu, 55100 Kuala Lumpur',
    operatingDays: 'Isnin - Sabtu',
    operatingHours: '06:30 - 16:00',
    typeOfFood: 'Cham Peng Kaw, Hor Fun Sup Ayam Kampung & Chee Cheong Fun',
    bankName: 'Public Bank Berhad',
    bankAccountName: 'Kopitiam Ah Kow 1958 Enterprise',
    bankAccountNumber: '4091829401',
    status: 'Diluluskan',
    agentName: 'Siti Sarah binti Yusoff',
    date: new Date('2026-09-07T07:45:00Z'),
    yesScore: 9,
    leadStatus: 'Qualified Lead',
    targetPlatform: 'GrabFood',
    notes: 'Resipi warisan 3 generasi, popular dalam kalangan penduduk tempatan Pudu.',
  },
  {
    memberNo: 'LC-MBR-2026-008',
    businessName: 'Sate Kajang Pak Din Family Kitchen',
    fullName: 'Kamaruddin bin Din',
    registrationNo: '202101038472-P',
    icPassportNo: '710822-10-5341',
    dateOfBirth: '22/08/1971',
    age: '55',
    gender: 'Lelaki',
    race: 'Melayu',
    religion: 'Islam',
    contactNumber: '+60 19-204 8812',
    emailAddress: 'satekajang.pakdin@gmail.com',
    storeAddress: 'Lot 10, Jalan Reko, 43000 Kajang, Selangor',
    operatingDays: 'Setiap Hari',
    operatingHours: '16:00 - 23:30',
    typeOfFood: 'Sate Daging, Sate Ayam, Nasi Impit & Kuah Kacang Pekat Resipi Khas',
    bankName: 'RHB Bank Berhad',
    bankAccountName: 'Sate Kajang Pak Din Family Kitchen',
    bankAccountNumber: '21203900192831',
    status: 'Diluluskan',
    agentName: 'Siti Sarah binti Yusoff',
    date: new Date('2026-09-08T16:00:00Z'),
    yesScore: 10,
    leadStatus: 'Hot Lead',
    targetPlatform: 'Foodpanda & GrabFood',
    notes: 'Jualan malam yang konsisten dengan tempahan katering dan bawa pulang.',
  },
  {
    memberNo: 'LC-MBR-2026-009',
    businessName: 'Restoran Ikan Bakar Bellamy Port',
    fullName: 'Norzila binti Aziz',
    registrationNo: '202301029184-H',
    icPassportNo: '790415-08-5928',
    dateOfBirth: '15/04/1979',
    age: '47',
    gender: 'Wanita',
    race: 'Melayu',
    religion: 'Islam',
    contactNumber: '+60 13-774 2190',
    emailAddress: 'ikanbakar.bellamy@gmail.com',
    storeAddress: 'Gerai No. 8, Medan Ikan Bakar Bellamy, Jalan Bellamy, 50460 KL',
    operatingDays: 'Isnin - Sabtu',
    operatingHours: '11:00 - 16:30',
    typeOfFood: 'Ikan Pari Bakar Sambal, Sotong Bakar Arang & Air Asam Kerisik',
    bankName: 'CIMB Bank Berhad',
    bankAccountName: 'Restoran Ikan Bakar Bellamy Port',
    bankAccountNumber: '705819284012',
    status: 'Dalam Proses',
    agentName: 'Siti Sarah binti Yusoff',
    date: new Date('2026-09-09T11:30:00Z'),
    yesScore: 8,
    leadStatus: 'Qualified Lead',
    targetPlatform: 'ShopeeFood',
    notes: 'Sedang menunggu pengesahan sijil pengendalian makanan pekerja.',
  },
  {
    memberNo: 'LC-MBR-2026-010',
    businessName: 'Uncle Lim Hainan Delights Sdn Bhd',
    fullName: 'Lim Guan Hock',
    registrationNo: '202401028391-B',
    icPassportNo: '730812-07-5291',
    dateOfBirth: '12/08/1973',
    age: '53',
    gender: 'Lelaki',
    race: 'Cina',
    religion: 'Kristian',
    contactNumber: '+60 16-554 8123',
    emailAddress: 'unclelim.bangsar@gmail.com',
    storeAddress: 'No 45, Jalan Telawi 3, Bangsar Baru, 59100 Kuala Lumpur',
    operatingDays: 'Setiap Hari',
    operatingHours: '09:00 - 22:00',
    typeOfFood: 'Hainanese Chicken Chop, Roti Kahwin, Mee Siam & Hainan Tea',
    bankName: 'Malayan Banking Berhad (Maybank)',
    bankAccountName: 'Uncle Lim Hainan Delights Sdn Bhd',
    bankAccountNumber: '514892019482',
    status: 'Diluluskan',
    agentName: 'Siti Sarah binti Yusoff',
    date: new Date('2026-09-10T10:00:00Z'),
    yesScore: 10,
    leadStatus: 'Hot Lead',
    targetPlatform: 'GrabFood',
    notes: 'Terletak di kawasan elit Bangsar Baru, menu gabungan sarapan dan makan malam.',
  },
];

async function seedAllTenMerchants() {
  console.log('🚀 Seeding all 10 audited merchants into BusinessRegistration, Checklists & Merchants...');

  // 1. Clear existing registrations & checklists to prevent duplicates
  await prisma.businessRegistration.deleteMany();
  await prisma.merchantChecklist.deleteMany();

  for (const m of merchantsData) {
    // 2. Create BusinessRegistration record
    await prisma.businessRegistration.create({
      data: {
        date: m.date,
        memberNo: m.memberNo,
        fullName: m.fullName,
        businessName: m.businessName,
        registrationNo: m.registrationNo,
        icPassportNo: m.icPassportNo,
        dateOfBirth: m.dateOfBirth,
        age: m.age,
        gender: m.gender,
        race: m.race,
        religion: m.religion,
        nationality: 'Warganegara Malaysia',
        contactNumber: m.contactNumber,
        emailAddress: m.emailAddress,
        storeAddress: m.storeAddress,
        mailingAddress: m.storeAddress,
        operatingDays: m.operatingDays,
        operatingHours: m.operatingHours,
        typeOfFood: m.typeOfFood,
        bankName: m.bankName,
        bankAccountName: m.bankAccountName,
        bankAccountNumber: m.bankAccountNumber,
        documentsChecklist: JSON.stringify({
          icCopy: true,
          ssmCopy: true,
          bankStatement: true,
          shopPhoto: true,
          typhoidCert: m.status === 'Diluluskan',
        }),
        receivedDate: m.date,
        processingOfficer: 'Siti Nurhaliza',
        status: m.status,
        activationDate: m.status === 'Diluluskan' ? new Date(m.date.getTime() + 2 * 86400000) : null,
        agreedToTerms: true,
        merchantSignatureName: m.fullName,
        merchantSignatureIc: m.icPassportNo,
        merchantSignatureDate: m.date,
        agentSignatureName: m.agentName,
        reviewerName: 'Siti Nurhaliza',
        approverName: 'Wai Yan Bo',
        language: 'EN',
      }
    });

    // 3. Create MerchantChecklist record
    await prisma.merchantChecklist.create({
      data: {
        agentName: m.agentName,
        date: m.date,
        merchant: m.businessName,
        personInCharge: m.fullName,
        mobileNumber: m.contactNumber,
        emailAddress: m.emailAddress,
        outletAddress: m.storeAddress,
        numberOfOutlets: 1,
        businessType: 'Restoran Fizikal & Penghantaran',
        targetPlatform: m.targetPlatform,
        leadStatus: m.leadStatus,
        language: 'EN',
        agentSelfCheck: JSON.stringify({
          signboardOk: true,
          deviceReady: true,
          kitchenClean: true,
          menuStandardized: true,
        }),
        agentNotes: m.notes,
        qualificationCheck: JSON.stringify({
          licenseValid: 'YES',
          deviceAvailable: 'YES',
          internetStable: 'YES',
          bankAccountActive: 'YES',
          packagingReady: 'YES',
          hygieneStandard: 'YES',
          commissionAgreed: 'YES',
          onboardingReady: 'YES',
          halalCertified: m.religion === 'Islam' ? 'YES' : 'NA',
          marketingPromoAgreed: 'YES',
        }),
        yesScore: m.yesScore,
        noScore: 10 - m.yesScore,
        naScore: m.religion === 'Islam' ? 0 : 1,
        totalChecked: 10,
      }
    });

    // 4. Also register into Merchant & Storefront if not exists so it shows in dashboard dropdowns
    let existingMerchant = await prisma.merchant.findFirst({
      where: { contactEmail: m.emailAddress }
    });
    if (!existingMerchant) {
      existingMerchant = await prisma.merchant.create({
        data: {
          name: m.fullName,
          businessName: m.businessName,
          contactEmail: m.emailAddress,
          contactPhone: m.contactNumber,
          status: 'ACTIVE',
        }
      });
      const slug = m.emailAddress.split('@')[0].replace(/[^a-z0-9]/g, '');
      await prisma.storefront.create({
        data: {
          merchantId: existingMerchant.id,
          grabEmail: `${slug}@grabfood.com`,
          name: m.businessName,
          isActive: true,
        }
      });
    }
  }

  console.log('\n=============================================================');
  console.log(`🎉 ALL 10 MERCHANTS SUCCESSFULLY POPULATED INTO DATABASE!`);
  console.log(`• Merchant Registrations: 10 total records`);
  console.log(`• Merchant Checklists:    10 total records`);
  console.log(`• Connected Storefronts:  10 active GrabFood stores`);
  console.log('=============================================================\n');

  await prisma.$disconnect();
}

seedAllTenMerchants().catch((err) => {
  console.error('Error seeding merchants:', err);
  process.exit(1);
});
